VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "Feuil1"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = True
Attribute VB_Exposed = True
Sub main()
    Range("AE33").Name = "Entree"
    Range("X30").Name = "T306"
    Range("Z26").Name = "Acceuil"
    Range("BH24").Name = "Restauration"
    Range("F23").Name = "Chateau"
    Range("Z18").Name = "Salle"
    Range("AC18").Name = "P108"
    Range("AF14").Name = "BU"
End Sub
